### ISSUE TITLE
Severe graphics tearing and wrong/missing textures

### ISSUE THREAD

**Issue by thetommah** [xemu-project/xemu-website#128]
All games I've tested work great one 1 PC but on my 2nd PC a lot of models and graphics have severe tearing.  2d assets seem to tear diagonally and all particle effect (I think) seem to explode all over the scene and a lot of missing/incorrect textures. Games themselves play very smooth at ~30-40fps, so it's just the visuals.  Xbox menu and boot sequence plays perfectly, as does Halo 1 main menu.
AMD Radeon HD 6670
Windows 10 64-bit
![Screenshot 2023-02-22 085719](https://user-images.githubusercontent.com/95310316/220814929-a05b9130-9f4d-4c9d-b1ba-1af123d0ac23.png)
![Screenshot 2023-02-22 085323](https://user-images.githubusercontent.com/95310316/220814940-d12ee16a-c8d2-46b5-a8b9-7fffdf7874bd.png)
![image](https://user-images.githubusercontent.com/95310316/220814948-3de34b11-3314-4b0d-ab15-644413ae4085.png)

**Comment by mborgerson** [comment]
Thanks for reporting. This repo is for the website. Issues about xemu itself should be filed on the https://github.com/xemu-project/xemu repo. That said, this appears to be an issue with the graphics drivers on your AMD Radeon HD 6670.
