### ISSUE TITLE
[CSS] Navigation overflows over footer when expanding development and debugging

### ISSUE THREAD

**Issue by flleeppyy** [xemu-project/xemu-website#131]
When expanding the development nav item, and the debugging item under that, the page will overflow after the header when scrolling down. Items are accessible when you scroll down far enough but it's not convenient.
![image](https://github.com/xemu-project/xemu-website/assets/18307183/c6bfc55a-a986-4492-8d74-8b16adceaac2)

Also, the parts of the navigation bar will be inaccessible if the page does not scroll/ the viewport is too small

![image](https://github.com/xemu-project/xemu-website/assets/18307183/4ba6eb4d-f936-400b-9912-33736f166547)

I would make a pull request but CSS is not my strong suit.

**Comment by mborgerson** [comment]
Is this still an issue? I can't reproduce it

**Comment by flleeppyy** [comment]
Doesn't seem to be an issue anymore.

**Comment by dekay** [comment]
Works for me too now, and I had reported the dup in #150.
