### ISSUE TITLE
Contribuição (Help)

### ISSUE THREAD

**Issue by Skarzyll** [xemu-project/xemu-website#141]
Como eu posso contribuir para site do projeto? Queria contribuir, modificar e estudar, além de ganhar mais experiência em projetos em conjunto. Eu tentei simplesmente abrir pelo vscode, mas infelizmente não funcionou.

How can i contribute to the project website? I wanted to contribute, modify and study, as well as gain more expirence in joint projects. I tried simply opening it through vscode, but unfortunately it didn't work.

**Comment by antangelo** [comment]
The readme contains instructions on how to clone, build and serve the website source locally. From there you can study the code on your own or work on one of the issues and submit a pull request.

If you have any questions about contributing feel free to ask on the project discord: https://discord.gg/ayyjsuM
