### ISSUE TITLE
Website seach field is missing

### ISSUE THREAD

**Issue by dekay** [xemu-project/xemu-website#149]
According to Matt from a discussion on Discord today, the xemu website is built to have a search function. It appears that this is either missing or disabled. This is in Firefox on Linux  and happens with and without my adblocker disabled.

![image](https://github.com/xemu-project/xemu-website/assets/59916/b5fb78b5-446d-4b6c-803d-884e67db3aac)

**Comment by mborgerson** [comment]
Fixed in ed9c35c64f9ca8585b9a0524c595ed8c3146bee0
