### ISSUE TITLE
Website navigation bar at left can get messed up

### ISSUE THREAD

**Issue by dekay** [xemu-project/xemu-website#150]
If the navigation bar on the left side of the window is expanded such that it spills into the bottom of the window, the navigation text overlaps the xemu copyright notice.
![image](https://github.com/xemu-project/xemu-website/assets/59916/70b0e68c-8ce6-4399-808e-ac3761452214)

If the browser is then resized smaller vertically by dragging up the bottom of the window, the copyright notice moves up over top of the navigation text. Weirder still, here I have expanded the "Debugging" submenu but left scroll of the mouse won't reveal the items below. I have to vertically expand the window to see the items below. Basically, this sequence of events seems to break the vertical scroll of the left nav pane.

![image](https://github.com/xemu-project/xemu-website/assets/59916/d7a59de5-4b9f-4cb1-8439-e61c396e0942)

This on Firefox on Linux with adblockers disabled.

**Comment by dekay** [comment]
I just noticed that the spillover can happen on the right side as well. This is the FAQ page, and the list of questions spills on top of the social media icons at the bottom of the page.

![image](https://github.com/xemu-project/xemu-website/assets/59916/3d6d19a6-b68e-486b-87d2-7eee52b2c632)

**Comment by mborgerson** [comment]
Dup #131
