### ISSUE TITLE
xemu.app/docs/download/#flatpak: flatpak override can be used instead of flatseal

### ISSUE THREAD

**Issue by davidhedlund** [xemu-project/xemu-website#156]
### Bug Description

From https://xemu.app/docs/download/#flatpak

"When using the flatpak installation method, only the ~/.var/app/app.xemu.xemu/data/xemu/xemu directory can be written to by xemu. The Hard Disk image must be placed there, for example at ~/.var/app/app.xemu.xemu/data/xemu/xemu/xbox_hdd.qcow2.

If you want to whitelist additional directories, you can [do so with Flatseal](https://xemu.app/docs/troubleshooting/#flatpak-release-will-not-load-bios-mcpx-rom-hard-drive)."

# Proposed text
While Flatseal is a useful tool for managing Flatpak permissions, utilizing the built-in command-line options provides a simpler and more direct approach for users who need to adjust directory access for xemu.

Flatpak's command-line overrides, which are simpler and do not require the installation of an additional application like Flatseal.

I recommend that you replace this text at https://xemu.app/docs/download/#flatpak
```
If you want to whitelist additional directories, you can [do so with Flatseal](https://xemu.app/docs/troubleshooting/#flatpak-release-will-not-load-bios-mcpx-rom-hard-drive)."
```

with this text:

```
If you want to whitelist additional directories, you can with `sudo flatpak override app.xemu.xemu --filesystem`. Example:

`sudo flatpak override app.xemu.xemu --filesystem="$HOME/savedgames/xemu/"`
* Note: sudo is required by xemu, using --user instead like this will not work: `flatpak override app.xemu.xemu --user --filesystem="$HOME/savedgames/xemu/"`
```

**Comment by mborgerson** [comment]
I'll close this issue and ask that you instead send a PR with your proposed changes.

**Comment by davidhedlund** [comment]
> I'll close this issue and ask that you instead send a PR with your proposed changes.

Thank you.
